#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("checkbooks.Resource", IsApplication=true)]

namespace checkbooks
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int subtype_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int AddTransaction = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int Amount = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int RecentActivity = 2131099648;
			
			// aapt resource value: 0x7f060009
			public const int TransactionAmount = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int TransactionDate = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int TransactionRow = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int TransactionSubRow1 = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int TransactionSubRow2 = 2131099658;
			
			// aapt resource value: 0x7f060008
			public const int TransactionType = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int TypeSpinner = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int dollar = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TransactionItem = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int transaction_db = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
